// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: vision.proto

package vision

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OccupancyMap_Type int32

const (
	OccupancyMap_UNKNOWN  OccupancyMap_Type = 0
	OccupancyMap_EMPTY    OccupancyMap_Type = 1
	OccupancyMap_OCCUPIED OccupancyMap_Type = 2
	OccupancyMap_MERGED   OccupancyMap_Type = 3
)

// Enum value maps for OccupancyMap_Type.
var (
	OccupancyMap_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "EMPTY",
		2: "OCCUPIED",
		3: "MERGED",
	}
	OccupancyMap_Type_value = map[string]int32{
		"UNKNOWN":  0,
		"EMPTY":    1,
		"OCCUPIED": 2,
		"MERGED":   3,
	}
)

func (x OccupancyMap_Type) Enum() *OccupancyMap_Type {
	p := new(OccupancyMap_Type)
	*p = x
	return p
}

func (x OccupancyMap_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OccupancyMap_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_vision_proto_enumTypes[0].Descriptor()
}

func (OccupancyMap_Type) Type() protoreflect.EnumType {
	return &file_vision_proto_enumTypes[0]
}

func (x OccupancyMap_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OccupancyMap_Type.Descriptor instead.
func (OccupancyMap_Type) EnumDescriptor() ([]byte, []int) {
	return file_vision_proto_rawDescGZIP(), []int{3, 0}
}

type OccupancyMap_Scope int32

const (
	OccupancyMap_LOCAL  OccupancyMap_Scope = 0
	OccupancyMap_GLOBAL OccupancyMap_Scope = 1
)

// Enum value maps for OccupancyMap_Scope.
var (
	OccupancyMap_Scope_name = map[int32]string{
		0: "LOCAL",
		1: "GLOBAL",
	}
	OccupancyMap_Scope_value = map[string]int32{
		"LOCAL":  0,
		"GLOBAL": 1,
	}
)

func (x OccupancyMap_Scope) Enum() *OccupancyMap_Scope {
	p := new(OccupancyMap_Scope)
	*p = x
	return p
}

func (x OccupancyMap_Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OccupancyMap_Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_vision_proto_enumTypes[1].Descriptor()
}

func (OccupancyMap_Scope) Type() protoreflect.EnumType {
	return &file_vision_proto_enumTypes[1]
}

func (x OccupancyMap_Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OccupancyMap_Scope.Descriptor instead.
func (OccupancyMap_Scope) EnumDescriptor() ([]byte, []int) {
	return file_vision_proto_rawDescGZIP(), []int{3, 1}
}

type OccupancyMap_Compression int32

const (
	OccupancyMap_RAW  OccupancyMap_Compression = 0
	OccupancyMap_GZ   OccupancyMap_Compression = 1
	OccupancyMap_ZSTD OccupancyMap_Compression = 2
	OccupancyMap_JPEG OccupancyMap_Compression = 3
	OccupancyMap_PNG  OccupancyMap_Compression = 4
)

// Enum value maps for OccupancyMap_Compression.
var (
	OccupancyMap_Compression_name = map[int32]string{
		0: "RAW",
		1: "GZ",
		2: "ZSTD",
		3: "JPEG",
		4: "PNG",
	}
	OccupancyMap_Compression_value = map[string]int32{
		"RAW":  0,
		"GZ":   1,
		"ZSTD": 2,
		"JPEG": 3,
		"PNG":  4,
	}
)

func (x OccupancyMap_Compression) Enum() *OccupancyMap_Compression {
	p := new(OccupancyMap_Compression)
	*p = x
	return p
}

func (x OccupancyMap_Compression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OccupancyMap_Compression) Descriptor() protoreflect.EnumDescriptor {
	return file_vision_proto_enumTypes[2].Descriptor()
}

func (OccupancyMap_Compression) Type() protoreflect.EnumType {
	return &file_vision_proto_enumTypes[2]
}

func (x OccupancyMap_Compression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OccupancyMap_Compression.Descriptor instead.
func (OccupancyMap_Compression) EnumDescriptor() ([]byte, []int) {
	return file_vision_proto_rawDescGZIP(), []int{3, 2}
}

type Color struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Red           float32                `protobuf:"fixed32,1,opt,name=red,proto3" json:"red,omitempty"`     // [0, 1]
	Green         float32                `protobuf:"fixed32,2,opt,name=green,proto3" json:"green,omitempty"` // [0, 1]
	Blue          float32                `protobuf:"fixed32,3,opt,name=blue,proto3" json:"blue,omitempty"`   // [0, 1]
	Alpha         *wrapperspb.FloatValue `protobuf:"bytes,4,opt,name=alpha,proto3" json:"alpha,omitempty"`   // [0, 1], unset = 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Color) Reset() {
	*x = Color{}
	mi := &file_vision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_vision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_vision_proto_rawDescGZIP(), []int{0}
}

func (x *Color) GetRed() float32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *Color) GetGreen() float32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *Color) GetBlue() float32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

func (x *Color) GetAlpha() *wrapperspb.FloatValue {
	if x != nil {
		return x.Alpha
	}
	return nil
}

type FramePrediction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"` // top left
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"` // top left
	Width         float32                `protobuf:"fixed32,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        float32                `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"`
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ClassId       int32                  `protobuf:"varint,6,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ClassName     string                 `protobuf:"bytes,7,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	ClassColor    *Color                 `protobuf:"bytes,8,opt,name=class_color,json=classColor,proto3" json:"class_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FramePrediction) Reset() {
	*x = FramePrediction{}
	mi := &file_vision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FramePrediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FramePrediction) ProtoMessage() {}

func (x *FramePrediction) ProtoReflect() protoreflect.Message {
	mi := &file_vision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FramePrediction.ProtoReflect.Descriptor instead.
func (*FramePrediction) Descriptor() ([]byte, []int) {
	return file_vision_proto_rawDescGZIP(), []int{1}
}

func (x *FramePrediction) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *FramePrediction) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *FramePrediction) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FramePrediction) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FramePrediction) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *FramePrediction) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *FramePrediction) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *FramePrediction) GetClassColor() *Color {
	if x != nil {
		return x.ClassColor
	}
	return nil
}

type Frame struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FrameNumber          uint64                 `protobuf:"varint,1,opt,name=frame_number,json=frameNumber,proto3" json:"frame_number,omitempty"`
	TtagSystem           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ttag_system,json=ttagSystem,proto3" json:"ttag_system,omitempty"`
	TtagSteadyNs         uint64                 `protobuf:"varint,3,opt,name=ttag_steady_ns,json=ttagSteadyNs,proto3" json:"ttag_steady_ns,omitempty"`
	PredictionDurationMs uint32                 `protobuf:"varint,4,opt,name=prediction_duration_ms,json=predictionDurationMs,proto3" json:"prediction_duration_ms,omitempty"`
	Predictions          []*FramePrediction     `protobuf:"bytes,5,rep,name=predictions,proto3" json:"predictions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_vision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_vision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_vision_proto_rawDescGZIP(), []int{2}
}

func (x *Frame) GetFrameNumber() uint64 {
	if x != nil {
		return x.FrameNumber
	}
	return 0
}

func (x *Frame) GetTtagSystem() *timestamppb.Timestamp {
	if x != nil {
		return x.TtagSystem
	}
	return nil
}

func (x *Frame) GetTtagSteadyNs() uint64 {
	if x != nil {
		return x.TtagSteadyNs
	}
	return 0
}

func (x *Frame) GetPredictionDurationMs() uint32 {
	if x != nil {
		return x.PredictionDurationMs
	}
	return 0
}

func (x *Frame) GetPredictions() []*FramePrediction {
	if x != nil {
		return x.Predictions
	}
	return nil
}

type OccupancyMap struct {
	state        protoimpl.MessageState   `protogen:"open.v1"`
	TtagSystem   *timestamppb.Timestamp   `protobuf:"bytes,1,opt,name=ttag_system,json=ttagSystem,proto3" json:"ttag_system,omitempty"`
	TtagSteadyNs uint64                   `protobuf:"varint,2,opt,name=ttag_steady_ns,json=ttagSteadyNs,proto3" json:"ttag_steady_ns,omitempty"`
	Type         OccupancyMap_Type        `protobuf:"varint,3,opt,name=type,proto3,enum=magothy.protobuf.vision.OccupancyMap_Type" json:"type,omitempty"`
	Scope        OccupancyMap_Scope       `protobuf:"varint,11,opt,name=scope,proto3,enum=magothy.protobuf.vision.OccupancyMap_Scope" json:"scope,omitempty"`
	Compression  OccupancyMap_Compression `protobuf:"varint,12,opt,name=compression,proto3,enum=magothy.protobuf.vision.OccupancyMap_Compression" json:"compression,omitempty"`
	LatDeg       float64                  `protobuf:"fixed64,4,opt,name=lat_deg,json=latDeg,proto3" json:"lat_deg,omitempty"`          // center of map
	LonDeg       float64                  `protobuf:"fixed64,5,opt,name=lon_deg,json=lonDeg,proto3" json:"lon_deg,omitempty"`          // center of map
	TlLatDeg     float64                  `protobuf:"fixed64,13,opt,name=tl_lat_deg,json=tlLatDeg,proto3" json:"tl_lat_deg,omitempty"` // top left
	TlLonDeg     float64                  `protobuf:"fixed64,14,opt,name=tl_lon_deg,json=tlLonDeg,proto3" json:"tl_lon_deg,omitempty"` // top left
	BrLatDeg     float64                  `protobuf:"fixed64,15,opt,name=br_lat_deg,json=brLatDeg,proto3" json:"br_lat_deg,omitempty"` // bottom right
	BrLonDeg     float64                  `protobuf:"fixed64,16,opt,name=br_lon_deg,json=brLonDeg,proto3" json:"br_lon_deg,omitempty"` // bottom right
	WidthM       float64                  `protobuf:"fixed64,6,opt,name=width_m,json=widthM,proto3" json:"width_m,omitempty"`
	HeightM      float64                  `protobuf:"fixed64,7,opt,name=height_m,json=heightM,proto3" json:"height_m,omitempty"`
	WidthPx      uint32                   `protobuf:"varint,8,opt,name=width_px,json=widthPx,proto3" json:"width_px,omitempty"`
	HeightPx     uint32                   `protobuf:"varint,9,opt,name=height_px,json=heightPx,proto3" json:"height_px,omitempty"`
	// size == width_px * height_px, row-major order
	// first pixel is top-left
	// 1 byte per pixel, 0-255 belief
	// 0 = no belief, 255 = full belief
	Grid          []byte `protobuf:"bytes,10,opt,name=grid,proto3" json:"grid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OccupancyMap) Reset() {
	*x = OccupancyMap{}
	mi := &file_vision_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OccupancyMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OccupancyMap) ProtoMessage() {}

func (x *OccupancyMap) ProtoReflect() protoreflect.Message {
	mi := &file_vision_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OccupancyMap.ProtoReflect.Descriptor instead.
func (*OccupancyMap) Descriptor() ([]byte, []int) {
	return file_vision_proto_rawDescGZIP(), []int{3}
}

func (x *OccupancyMap) GetTtagSystem() *timestamppb.Timestamp {
	if x != nil {
		return x.TtagSystem
	}
	return nil
}

func (x *OccupancyMap) GetTtagSteadyNs() uint64 {
	if x != nil {
		return x.TtagSteadyNs
	}
	return 0
}

func (x *OccupancyMap) GetType() OccupancyMap_Type {
	if x != nil {
		return x.Type
	}
	return OccupancyMap_UNKNOWN
}

func (x *OccupancyMap) GetScope() OccupancyMap_Scope {
	if x != nil {
		return x.Scope
	}
	return OccupancyMap_LOCAL
}

func (x *OccupancyMap) GetCompression() OccupancyMap_Compression {
	if x != nil {
		return x.Compression
	}
	return OccupancyMap_RAW
}

func (x *OccupancyMap) GetLatDeg() float64 {
	if x != nil {
		return x.LatDeg
	}
	return 0
}

func (x *OccupancyMap) GetLonDeg() float64 {
	if x != nil {
		return x.LonDeg
	}
	return 0
}

func (x *OccupancyMap) GetTlLatDeg() float64 {
	if x != nil {
		return x.TlLatDeg
	}
	return 0
}

func (x *OccupancyMap) GetTlLonDeg() float64 {
	if x != nil {
		return x.TlLonDeg
	}
	return 0
}

func (x *OccupancyMap) GetBrLatDeg() float64 {
	if x != nil {
		return x.BrLatDeg
	}
	return 0
}

func (x *OccupancyMap) GetBrLonDeg() float64 {
	if x != nil {
		return x.BrLonDeg
	}
	return 0
}

func (x *OccupancyMap) GetWidthM() float64 {
	if x != nil {
		return x.WidthM
	}
	return 0
}

func (x *OccupancyMap) GetHeightM() float64 {
	if x != nil {
		return x.HeightM
	}
	return 0
}

func (x *OccupancyMap) GetWidthPx() uint32 {
	if x != nil {
		return x.WidthPx
	}
	return 0
}

func (x *OccupancyMap) GetHeightPx() uint32 {
	if x != nil {
		return x.HeightPx
	}
	return 0
}

func (x *OccupancyMap) GetGrid() []byte {
	if x != nil {
		return x.Grid
	}
	return nil
}

type ObjectTrack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TtagSystem    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ttag_system,json=ttagSystem,proto3" json:"ttag_system,omitempty"`
	TtagSteadyNs  uint64                 `protobuf:"varint,2,opt,name=ttag_steady_ns,json=ttagSteadyNs,proto3" json:"ttag_steady_ns,omitempty"`
	TrackId       int32                  `protobuf:"varint,3,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	BranchId      int32                  `protobuf:"varint,4,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	SourceId      int32                  `protobuf:"varint,5,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`          // source of the track, e.g. sensor ID, tracker ID
	AgeS          float32                `protobuf:"fixed32,6,opt,name=age_s,json=ageS,proto3" json:"age_s,omitempty"`                     // total time object is being tracked
	UpdateCount   int32                  `protobuf:"varint,7,opt,name=update_count,json=updateCount,proto3" json:"update_count,omitempty"` // number of times track is updated
	LatitudeDeg   float64                `protobuf:"fixed64,8,opt,name=latitude_deg,json=latitudeDeg,proto3" json:"latitude_deg,omitempty"`
	LongitudeDeg  float64                `protobuf:"fixed64,9,opt,name=longitude_deg,json=longitudeDeg,proto3" json:"longitude_deg,omitempty"`
	HeadingDeg    float64                `protobuf:"fixed64,10,opt,name=heading_deg,json=headingDeg,proto3" json:"heading_deg,omitempty"`
	SpeedMps      float64                `protobuf:"fixed64,11,opt,name=speed_mps,json=speedMps,proto3" json:"speed_mps,omitempty"`
	Covariance    []float32              `protobuf:"fixed32,12,rep,packed,name=covariance,proto3" json:"covariance,omitempty"`              // 4x4 row-major covariance matrix
	IsConfirmed   bool                   `protobuf:"varint,13,opt,name=is_confirmed,json=isConfirmed,proto3" json:"is_confirmed,omitempty"` // is track tentative or confirmed
	IsPredicted   bool                   `protobuf:"varint,14,opt,name=is_predicted,json=isPredicted,proto3" json:"is_predicted,omitempty"` // is position/velocity predicted (and not corrected)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectTrack) Reset() {
	*x = ObjectTrack{}
	mi := &file_vision_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectTrack) ProtoMessage() {}

func (x *ObjectTrack) ProtoReflect() protoreflect.Message {
	mi := &file_vision_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectTrack.ProtoReflect.Descriptor instead.
func (*ObjectTrack) Descriptor() ([]byte, []int) {
	return file_vision_proto_rawDescGZIP(), []int{4}
}

func (x *ObjectTrack) GetTtagSystem() *timestamppb.Timestamp {
	if x != nil {
		return x.TtagSystem
	}
	return nil
}

func (x *ObjectTrack) GetTtagSteadyNs() uint64 {
	if x != nil {
		return x.TtagSteadyNs
	}
	return 0
}

func (x *ObjectTrack) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *ObjectTrack) GetBranchId() int32 {
	if x != nil {
		return x.BranchId
	}
	return 0
}

func (x *ObjectTrack) GetSourceId() int32 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *ObjectTrack) GetAgeS() float32 {
	if x != nil {
		return x.AgeS
	}
	return 0
}

func (x *ObjectTrack) GetUpdateCount() int32 {
	if x != nil {
		return x.UpdateCount
	}
	return 0
}

func (x *ObjectTrack) GetLatitudeDeg() float64 {
	if x != nil {
		return x.LatitudeDeg
	}
	return 0
}

func (x *ObjectTrack) GetLongitudeDeg() float64 {
	if x != nil {
		return x.LongitudeDeg
	}
	return 0
}

func (x *ObjectTrack) GetHeadingDeg() float64 {
	if x != nil {
		return x.HeadingDeg
	}
	return 0
}

func (x *ObjectTrack) GetSpeedMps() float64 {
	if x != nil {
		return x.SpeedMps
	}
	return 0
}

func (x *ObjectTrack) GetCovariance() []float32 {
	if x != nil {
		return x.Covariance
	}
	return nil
}

func (x *ObjectTrack) GetIsConfirmed() bool {
	if x != nil {
		return x.IsConfirmed
	}
	return false
}

func (x *ObjectTrack) GetIsPredicted() bool {
	if x != nil {
		return x.IsPredicted
	}
	return false
}

type ObjectTrackList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TtagSystem    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ttag_system,json=ttagSystem,proto3" json:"ttag_system,omitempty"`
	TtagSteadyNs  uint64                 `protobuf:"varint,2,opt,name=ttag_steady_ns,json=ttagSteadyNs,proto3" json:"ttag_steady_ns,omitempty"`
	SourceId      int32                  `protobuf:"varint,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // source of the track list
	Tracks        []*ObjectTrack         `protobuf:"bytes,4,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectTrackList) Reset() {
	*x = ObjectTrackList{}
	mi := &file_vision_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectTrackList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectTrackList) ProtoMessage() {}

func (x *ObjectTrackList) ProtoReflect() protoreflect.Message {
	mi := &file_vision_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectTrackList.ProtoReflect.Descriptor instead.
func (*ObjectTrackList) Descriptor() ([]byte, []int) {
	return file_vision_proto_rawDescGZIP(), []int{5}
}

func (x *ObjectTrackList) GetTtagSystem() *timestamppb.Timestamp {
	if x != nil {
		return x.TtagSystem
	}
	return nil
}

func (x *ObjectTrackList) GetTtagSteadyNs() uint64 {
	if x != nil {
		return x.TtagSteadyNs
	}
	return 0
}

func (x *ObjectTrackList) GetSourceId() int32 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *ObjectTrackList) GetTracks() []*ObjectTrack {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type Vertex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatitudeDeg   float64                `protobuf:"fixed64,1,opt,name=latitude_deg,json=latitudeDeg,proto3" json:"latitude_deg,omitempty"`
	LongitudeDeg  float64                `protobuf:"fixed64,2,opt,name=longitude_deg,json=longitudeDeg,proto3" json:"longitude_deg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vertex) Reset() {
	*x = Vertex{}
	mi := &file_vision_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vertex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vertex) ProtoMessage() {}

func (x *Vertex) ProtoReflect() protoreflect.Message {
	mi := &file_vision_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vertex.ProtoReflect.Descriptor instead.
func (*Vertex) Descriptor() ([]byte, []int) {
	return file_vision_proto_rawDescGZIP(), []int{6}
}

func (x *Vertex) GetLatitudeDeg() float64 {
	if x != nil {
		return x.LatitudeDeg
	}
	return 0
}

func (x *Vertex) GetLongitudeDeg() float64 {
	if x != nil {
		return x.LongitudeDeg
	}
	return 0
}

type TrackingFence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TtagSystem    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ttag_system,json=ttagSystem,proto3" json:"ttag_system,omitempty"`
	TtagSteadyNs  uint64                 `protobuf:"varint,2,opt,name=ttag_steady_ns,json=ttagSteadyNs,proto3" json:"ttag_steady_ns,omitempty"`
	Vertices      []*Vertex              `protobuf:"bytes,3,rep,name=vertices,proto3" json:"vertices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackingFence) Reset() {
	*x = TrackingFence{}
	mi := &file_vision_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingFence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingFence) ProtoMessage() {}

func (x *TrackingFence) ProtoReflect() protoreflect.Message {
	mi := &file_vision_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingFence.ProtoReflect.Descriptor instead.
func (*TrackingFence) Descriptor() ([]byte, []int) {
	return file_vision_proto_rawDescGZIP(), []int{7}
}

func (x *TrackingFence) GetTtagSystem() *timestamppb.Timestamp {
	if x != nil {
		return x.TtagSystem
	}
	return nil
}

func (x *TrackingFence) GetTtagSteadyNs() uint64 {
	if x != nil {
		return x.TtagSteadyNs
	}
	return 0
}

func (x *TrackingFence) GetVertices() []*Vertex {
	if x != nil {
		return x.Vertices
	}
	return nil
}

var File_vision_proto protoreflect.FileDescriptor

const file_vision_proto_rawDesc = "" +
	"\n" +
	"\fvision.proto\x12\x17magothy.protobuf.vision\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"v\n" +
	"\x05Color\x12\x10\n" +
	"\x03red\x18\x01 \x01(\x02R\x03red\x12\x14\n" +
	"\x05green\x18\x02 \x01(\x02R\x05green\x12\x12\n" +
	"\x04blue\x18\x03 \x01(\x02R\x04blue\x121\n" +
	"\x05alpha\x18\x04 \x01(\v2\x1b.google.protobuf.FloatValueR\x05alpha\"\xf6\x01\n" +
	"\x0fFramePrediction\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x02R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x02R\x06height\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12\x19\n" +
	"\bclass_id\x18\x06 \x01(\x05R\aclassId\x12\x1d\n" +
	"\n" +
	"class_name\x18\a \x01(\tR\tclassName\x12?\n" +
	"\vclass_color\x18\b \x01(\v2\x1e.magothy.protobuf.vision.ColorR\n" +
	"classColor\"\x8f\x02\n" +
	"\x05Frame\x12!\n" +
	"\fframe_number\x18\x01 \x01(\x04R\vframeNumber\x12;\n" +
	"\vttag_system\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"ttagSystem\x12$\n" +
	"\x0ettag_steady_ns\x18\x03 \x01(\x04R\fttagSteadyNs\x124\n" +
	"\x16prediction_duration_ms\x18\x04 \x01(\rR\x14predictionDurationMs\x12J\n" +
	"\vpredictions\x18\x05 \x03(\v2(.magothy.protobuf.vision.FramePredictionR\vpredictions\"\x8a\x06\n" +
	"\fOccupancyMap\x12;\n" +
	"\vttag_system\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"ttagSystem\x12$\n" +
	"\x0ettag_steady_ns\x18\x02 \x01(\x04R\fttagSteadyNs\x12>\n" +
	"\x04type\x18\x03 \x01(\x0e2*.magothy.protobuf.vision.OccupancyMap.TypeR\x04type\x12A\n" +
	"\x05scope\x18\v \x01(\x0e2+.magothy.protobuf.vision.OccupancyMap.ScopeR\x05scope\x12S\n" +
	"\vcompression\x18\f \x01(\x0e21.magothy.protobuf.vision.OccupancyMap.CompressionR\vcompression\x12\x17\n" +
	"\alat_deg\x18\x04 \x01(\x01R\x06latDeg\x12\x17\n" +
	"\alon_deg\x18\x05 \x01(\x01R\x06lonDeg\x12\x1c\n" +
	"\n" +
	"tl_lat_deg\x18\r \x01(\x01R\btlLatDeg\x12\x1c\n" +
	"\n" +
	"tl_lon_deg\x18\x0e \x01(\x01R\btlLonDeg\x12\x1c\n" +
	"\n" +
	"br_lat_deg\x18\x0f \x01(\x01R\bbrLatDeg\x12\x1c\n" +
	"\n" +
	"br_lon_deg\x18\x10 \x01(\x01R\bbrLonDeg\x12\x17\n" +
	"\awidth_m\x18\x06 \x01(\x01R\x06widthM\x12\x19\n" +
	"\bheight_m\x18\a \x01(\x01R\aheightM\x12\x19\n" +
	"\bwidth_px\x18\b \x01(\rR\awidthPx\x12\x1b\n" +
	"\theight_px\x18\t \x01(\rR\bheightPx\x12\x12\n" +
	"\x04grid\x18\n" +
	" \x01(\fR\x04grid\"8\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05EMPTY\x10\x01\x12\f\n" +
	"\bOCCUPIED\x10\x02\x12\n" +
	"\n" +
	"\x06MERGED\x10\x03\"\x1e\n" +
	"\x05Scope\x12\t\n" +
	"\x05LOCAL\x10\x00\x12\n" +
	"\n" +
	"\x06GLOBAL\x10\x01\";\n" +
	"\vCompression\x12\a\n" +
	"\x03RAW\x10\x00\x12\x06\n" +
	"\x02GZ\x10\x01\x12\b\n" +
	"\x04ZSTD\x10\x02\x12\b\n" +
	"\x04JPEG\x10\x03\x12\a\n" +
	"\x03PNG\x10\x04\"\xe9\x03\n" +
	"\vObjectTrack\x12;\n" +
	"\vttag_system\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"ttagSystem\x12$\n" +
	"\x0ettag_steady_ns\x18\x02 \x01(\x04R\fttagSteadyNs\x12\x19\n" +
	"\btrack_id\x18\x03 \x01(\x05R\atrackId\x12\x1b\n" +
	"\tbranch_id\x18\x04 \x01(\x05R\bbranchId\x12\x1b\n" +
	"\tsource_id\x18\x05 \x01(\x05R\bsourceId\x12\x13\n" +
	"\x05age_s\x18\x06 \x01(\x02R\x04ageS\x12!\n" +
	"\fupdate_count\x18\a \x01(\x05R\vupdateCount\x12!\n" +
	"\flatitude_deg\x18\b \x01(\x01R\vlatitudeDeg\x12#\n" +
	"\rlongitude_deg\x18\t \x01(\x01R\flongitudeDeg\x12\x1f\n" +
	"\vheading_deg\x18\n" +
	" \x01(\x01R\n" +
	"headingDeg\x12\x1b\n" +
	"\tspeed_mps\x18\v \x01(\x01R\bspeedMps\x12\x1e\n" +
	"\n" +
	"covariance\x18\f \x03(\x02R\n" +
	"covariance\x12!\n" +
	"\fis_confirmed\x18\r \x01(\bR\visConfirmed\x12!\n" +
	"\fis_predicted\x18\x0e \x01(\bR\visPredicted\"\xcf\x01\n" +
	"\x0fObjectTrackList\x12;\n" +
	"\vttag_system\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"ttagSystem\x12$\n" +
	"\x0ettag_steady_ns\x18\x02 \x01(\x04R\fttagSteadyNs\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\x05R\bsourceId\x12<\n" +
	"\x06tracks\x18\x04 \x03(\v2$.magothy.protobuf.vision.ObjectTrackR\x06tracks\"P\n" +
	"\x06Vertex\x12!\n" +
	"\flatitude_deg\x18\x01 \x01(\x01R\vlatitudeDeg\x12#\n" +
	"\rlongitude_deg\x18\x02 \x01(\x01R\flongitudeDeg\"\xaf\x01\n" +
	"\rTrackingFence\x12;\n" +
	"\vttag_system\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"ttagSystem\x12$\n" +
	"\x0ettag_steady_ns\x18\x02 \x01(\x04R\fttagSteadyNs\x12;\n" +
	"\bvertices\x18\x03 \x03(\v2\x1f.magothy.protobuf.vision.VertexR\bverticesb\x06proto3"

var (
	file_vision_proto_rawDescOnce sync.Once
	file_vision_proto_rawDescData []byte
)

func file_vision_proto_rawDescGZIP() []byte {
	file_vision_proto_rawDescOnce.Do(func() {
		file_vision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vision_proto_rawDesc), len(file_vision_proto_rawDesc)))
	})
	return file_vision_proto_rawDescData
}

var file_vision_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_vision_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_vision_proto_goTypes = []any{
	(OccupancyMap_Type)(0),        // 0: magothy.protobuf.vision.OccupancyMap.Type
	(OccupancyMap_Scope)(0),       // 1: magothy.protobuf.vision.OccupancyMap.Scope
	(OccupancyMap_Compression)(0), // 2: magothy.protobuf.vision.OccupancyMap.Compression
	(*Color)(nil),                 // 3: magothy.protobuf.vision.Color
	(*FramePrediction)(nil),       // 4: magothy.protobuf.vision.FramePrediction
	(*Frame)(nil),                 // 5: magothy.protobuf.vision.Frame
	(*OccupancyMap)(nil),          // 6: magothy.protobuf.vision.OccupancyMap
	(*ObjectTrack)(nil),           // 7: magothy.protobuf.vision.ObjectTrack
	(*ObjectTrackList)(nil),       // 8: magothy.protobuf.vision.ObjectTrackList
	(*Vertex)(nil),                // 9: magothy.protobuf.vision.Vertex
	(*TrackingFence)(nil),         // 10: magothy.protobuf.vision.TrackingFence
	(*wrapperspb.FloatValue)(nil), // 11: google.protobuf.FloatValue
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_vision_proto_depIdxs = []int32{
	11, // 0: magothy.protobuf.vision.Color.alpha:type_name -> google.protobuf.FloatValue
	3,  // 1: magothy.protobuf.vision.FramePrediction.class_color:type_name -> magothy.protobuf.vision.Color
	12, // 2: magothy.protobuf.vision.Frame.ttag_system:type_name -> google.protobuf.Timestamp
	4,  // 3: magothy.protobuf.vision.Frame.predictions:type_name -> magothy.protobuf.vision.FramePrediction
	12, // 4: magothy.protobuf.vision.OccupancyMap.ttag_system:type_name -> google.protobuf.Timestamp
	0,  // 5: magothy.protobuf.vision.OccupancyMap.type:type_name -> magothy.protobuf.vision.OccupancyMap.Type
	1,  // 6: magothy.protobuf.vision.OccupancyMap.scope:type_name -> magothy.protobuf.vision.OccupancyMap.Scope
	2,  // 7: magothy.protobuf.vision.OccupancyMap.compression:type_name -> magothy.protobuf.vision.OccupancyMap.Compression
	12, // 8: magothy.protobuf.vision.ObjectTrack.ttag_system:type_name -> google.protobuf.Timestamp
	12, // 9: magothy.protobuf.vision.ObjectTrackList.ttag_system:type_name -> google.protobuf.Timestamp
	7,  // 10: magothy.protobuf.vision.ObjectTrackList.tracks:type_name -> magothy.protobuf.vision.ObjectTrack
	12, // 11: magothy.protobuf.vision.TrackingFence.ttag_system:type_name -> google.protobuf.Timestamp
	9,  // 12: magothy.protobuf.vision.TrackingFence.vertices:type_name -> magothy.protobuf.vision.Vertex
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_vision_proto_init() }
func file_vision_proto_init() {
	if File_vision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vision_proto_rawDesc), len(file_vision_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vision_proto_goTypes,
		DependencyIndexes: file_vision_proto_depIdxs,
		EnumInfos:         file_vision_proto_enumTypes,
		MessageInfos:      file_vision_proto_msgTypes,
	}.Build()
	File_vision_proto = out.File
	file_vision_proto_goTypes = nil
	file_vision_proto_depIdxs = nil
}
