// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: sensor.proto

package sensor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Range_Type int32

const (
	Range_UNKNOWN    Range_Type = 0
	Range_ULTRASOUND Range_Type = 1
	Range_INFRARED   Range_Type = 2
	Range_LASER      Range_Type = 3
)

// Enum value maps for Range_Type.
var (
	Range_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "ULTRASOUND",
		2: "INFRARED",
		3: "LASER",
	}
	Range_Type_value = map[string]int32{
		"UNKNOWN":    0,
		"ULTRASOUND": 1,
		"INFRARED":   2,
		"LASER":      3,
	}
)

func (x Range_Type) Enum() *Range_Type {
	p := new(Range_Type)
	*p = x
	return p
}

func (x Range_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Range_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_sensor_proto_enumTypes[0].Descriptor()
}

func (Range_Type) Type() protoreflect.EnumType {
	return &file_sensor_proto_enumTypes[0]
}

func (x Range_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Range_Type.Descriptor instead.
func (Range_Type) EnumDescriptor() ([]byte, []int) {
	return file_sensor_proto_rawDescGZIP(), []int{0, 0}
}

type Range struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TtagSystem        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ttag_system,json=ttagSystem,proto3" json:"ttag_system,omitempty"`
	TtagSteadyNs      uint64                 `protobuf:"varint,2,opt,name=ttag_steady_ns,json=ttagSteadyNs,proto3" json:"ttag_steady_ns,omitempty"`
	Type              Range_Type             `protobuf:"varint,3,opt,name=type,proto3,enum=Range_Type" json:"type,omitempty"`
	RangeM            float64                `protobuf:"fixed64,4,opt,name=range_m,json=rangeM,proto3" json:"range_m,omitempty"`
	RangeUncertaintyM float64                `protobuf:"fixed64,5,opt,name=range_uncertainty_m,json=rangeUncertaintyM,proto3" json:"range_uncertainty_m,omitempty"`
	FieldOfViewDeg    float64                `protobuf:"fixed64,6,opt,name=field_of_view_deg,json=fieldOfViewDeg,proto3" json:"field_of_view_deg,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *Range) GetTtagSystem() *timestamppb.Timestamp {
	if x != nil {
		return x.TtagSystem
	}
	return nil
}

func (x *Range) GetTtagSteadyNs() uint64 {
	if x != nil {
		return x.TtagSteadyNs
	}
	return 0
}

func (x *Range) GetType() Range_Type {
	if x != nil {
		return x.Type
	}
	return Range_UNKNOWN
}

func (x *Range) GetRangeM() float64 {
	if x != nil {
		return x.RangeM
	}
	return 0
}

func (x *Range) GetRangeUncertaintyM() float64 {
	if x != nil {
		return x.RangeUncertaintyM
	}
	return 0
}

func (x *Range) GetFieldOfViewDeg() float64 {
	if x != nil {
		return x.FieldOfViewDeg
	}
	return 0
}

var File_sensor_proto protoreflect.FileDescriptor

var file_sensor_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xbd, 0x02, 0x0a, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x74, 0x74, 0x61,
	0x67, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x74, 0x74, 0x61, 0x67,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x74, 0x61, 0x67, 0x5f, 0x73,
	0x74, 0x65, 0x61, 0x64, 0x79, 0x5f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c,
	0x74, 0x74, 0x61, 0x67, 0x53, 0x74, 0x65, 0x61, 0x64, 0x79, 0x4e, 0x73, 0x12, 0x1f, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x12, 0x2e, 0x0a, 0x13, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f,
	0x75, 0x6e, 0x63, 0x65, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x74, 0x79, 0x5f, 0x6d, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x11, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x6e, 0x63, 0x65, 0x72, 0x74,
	0x61, 0x69, 0x6e, 0x74, 0x79, 0x4d, 0x12, 0x29, 0x0a, 0x11, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f,
	0x6f, 0x66, 0x5f, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x64, 0x65, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x66, 0x56, 0x69, 0x65, 0x77, 0x44, 0x65,
	0x67, 0x22, 0x3c, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x55, 0x4c, 0x54, 0x52, 0x41, 0x53,
	0x4f, 0x55, 0x4e, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x46, 0x52, 0x41, 0x52,
	0x45, 0x44, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x41, 0x53, 0x45, 0x52, 0x10, 0x03, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_sensor_proto_rawDescOnce sync.Once
	file_sensor_proto_rawDescData []byte
)

func file_sensor_proto_rawDescGZIP() []byte {
	file_sensor_proto_rawDescOnce.Do(func() {
		file_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sensor_proto_rawDesc), len(file_sensor_proto_rawDesc)))
	})
	return file_sensor_proto_rawDescData
}

var file_sensor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sensor_proto_goTypes = []any{
	(Range_Type)(0),               // 0: Range.Type
	(*Range)(nil),                 // 1: Range
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_sensor_proto_depIdxs = []int32{
	2, // 0: Range.ttag_system:type_name -> google.protobuf.Timestamp
	0, // 1: Range.type:type_name -> Range.Type
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sensor_proto_init() }
func file_sensor_proto_init() {
	if File_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sensor_proto_rawDesc), len(file_sensor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sensor_proto_goTypes,
		DependencyIndexes: file_sensor_proto_depIdxs,
		EnumInfos:         file_sensor_proto_enumTypes,
		MessageInfos:      file_sensor_proto_msgTypes,
	}.Build()
	File_sensor_proto = out.File
	file_sensor_proto_goTypes = nil
	file_sensor_proto_depIdxs = nil
}
